WITH movement_events AS (
    SELECT
        USER_ID,
        TIME_GRAIN,
        TIME_PERIOD_END,
        IS_ACQUIRED,
        IS_CHURNED,
        IS_RESURRECTED,
        FIRST_ACQUISITION_DATE_INFO,
        FIRST_CHURN_DATE_INFO,
        FIRST_RESURRECTION_DATE_INFO
    FROM {{ ref('int_user_status_calculate_movements_2') }}
)

SELECT
    USER_ID,
    TIME_GRAIN,
    TIME_PERIOD_END,
    IS_ACQUIRED,
    IS_CHURNED,
    IS_RESURRECTED,
    FIRST_ACQUISITION_DATE_INFO,
    FIRST_CHURN_DATE_INFO,
    FIRST_RESURRECTION_DATE_INFO
FROM movement_events
WHERE (IS_CHURNED = TRUE     AND FIRST_CHURN_DATE_INFO IS NULL)
   OR (IS_RESURRECTED = TRUE AND FIRST_RESURRECTION_DATE_INFO IS NULL)
   OR (IS_ACQUIRED = TRUE    AND FIRST_ACQUISITION_DATE_INFO  IS NULL)
