WITH period_snapshot AS (
    SELECT * FROM {{ ref('int_user_status_build_snapshots') }}
)

, periods_with_lag AS (
    SELECT
        USER_ID,
        TIME_GRAIN,
        TIME_PERIOD_END,
        LAG(TIME_PERIOD_END) OVER (PARTITION BY USER_ID, TIME_GRAIN ORDER BY TIME_PERIOD_END) AS ACTUAL_PREVIOUS_PERIOD,
        PREVIOUS_TIME_PERIOD_END                                                              AS EXPECTED_PREVIOUS_PERIOD
    FROM period_snapshot
)

SELECT
    USER_ID,
    TIME_GRAIN,
    TIME_PERIOD_END,
    ACTUAL_PREVIOUS_PERIOD,
    EXPECTED_PREVIOUS_PERIOD        
FROM periods_with_lag
WHERE ACTUAL_PREVIOUS_PERIOD IS NOT NULL
    AND ACTUAL_PREVIOUS_PERIOD IS DISTINCT FROM EXPECTED_PREVIOUS_PERIOD
