WITH period_snapshot AS (
    SELECT * FROM {{ ref('int_user_status_agg_snapshot') }}
)

, periods_with_lag AS (
    SELECT
        USER_ID,
        TIME_GRAIN,
        TIME_PERIOD,
        LAG(TIME_PERIOD) OVER (PARTITION BY USER_ID, TIME_GRAIN ORDER BY TIME_PERIOD) AS ACTUAL_PREVIOUS_PERIOD,
        PREVIOUS_TIME_PERIOD                                                          AS EXPECTED_PREVIOUS_PERIOD
    FROM period_snapshot
)

SELECT
    USER_ID,
    TIME_GRAIN,
    TIME_PERIOD,
    ACTUAL_PREVIOUS_PERIOD,
    EXPECTED_PREVIOUS_PERIOD        
FROM periods_with_lag
WHERE ACTUAL_PREVIOUS_PERIOD IS NOT NULL
    AND ACTUAL_PREVIOUS_PERIOD IS DISTINCT FROM EXPECTED_PREVIOUS_PERIOD
