WITH staged AS (
    SELECT
        CAST(USER_ID AS INTEGER) AS USER_ID,
        CAST(DATE_INFO AS DATE) AS DATE_INFO,
        CAST(STATUS AS VARCHAR) AS STATUS,
        STATUS = 'active' AS IS_ACTIVE,
        LAG(STATUS = 'active') OVER (PARTITION BY USER_ID ORDER BY DATE_INFO) AS PREVIOUS_IS_ACTIVE,
        CASE
            -- Return TRUE for the first [IS_ACTIVE] = TRUE at [USER_ID] level
            WHEN IS_ACTIVE = TRUE AND PREVIOUS_IS_ACTIVE IS NULL THEN TRUE
            WHEN MIN(CASE WHEN STATUS = 'active' THEN CAST(DATE_INFO AS DATE) ELSE NULL END) OVER (PARTITION BY USER_ID) = CAST(DATE_INFO AS DATE) THEN TRUE
            ELSE FALSE
        END AS IS_FIRST_USER_ACTIVE_DATE_INFO
    FROM {{ ref('raw_seed__subscription_status') }}
)

SELECT * FROM staged